report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        unpinned-requirements: false

fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
