all_message_bodies_http = [
    {
        "type": "message",
        "timestamp": {"nano": 732416000, "epochSecond": 1668603186},
        "messageType": "Incoming",
        "direction": "IN",
        "sessionId": "ds-lib-session1",
        "attachedEventIds": [],
        "messageId": "ds-lib-session1:first:1668603186732416801",
        "body": {
            "metadata": {
                "id": {"connectionId": {"sessionAlias": "ds-lib-session1"}, "sequence": "1668603186732416801"},
                "messageType": "Incoming",
                "protocol": "json",
            },
            "fields": {"a": {"simpleValue": "123"}},
        },
        "bodyBase64": "eyJhIjogIjEyMyJ9",
    },
    {
        "type": "message",
        "timestamp": {"nano": 306072000, "epochSecond": 1668603187},
        "messageType": "Outgoing",
        "direction": "OUT",
        "sessionId": "ds-lib-session1",
        "attachedEventIds": [],
        "messageId": "ds-lib-session1:second:1668603186732416803",
        "body": {
            "metadata": {
                "id": {
                    "connectionId": {"sessionAlias": "ds-lib-session1"},
                    "direction": "SECOND",
                    "sequence": "1668603186732416803",
                },
                "messageType": "Outgoing",
                "protocol": "json",
            },
            "fields": {"a": {"simpleValue": "123"}},
        },
        "bodyBase64": "eyJhIjogIjEyMyJ9",
    },
    {
        "type": "message",
        "timestamp": {"nano": 306072000, "epochSecond": 1668603187},
        "messageType": "Incoming",
        "direction": "IN",
        "sessionId": "ds-lib-session2",
        "attachedEventIds": [],
        "messageId": "ds-lib-session2:first:1668603186732416802",
        "body": {
            "metadata": {
                "id": {"connectionId": {"sessionAlias": "ds-lib-session2"}, "sequence": "1668603186732416802"},
                "messageType": "Incoming",
                "protocol": "json",
            },
            "fields": {"a": {"simpleValue": "123"}},
        },
        "bodyBase64": "eyJhIjogIjEyMyJ9",
    },
    {
        "type": "message",
        "timestamp": {"nano": 306072000, "epochSecond": 1668603187},
        "messageType": "Outgoing",
        "direction": "OUT",
        "sessionId": "ds-lib-session2",
        "attachedEventIds": [],
        "messageId": "ds-lib-session2:second:1668603186732416804",
        "body": {
            "metadata": {
                "id": {
                    "connectionId": {"sessionAlias": "ds-lib-session2"},
                    "direction": "SECOND",
                    "sequence": "1668603186732416804",
                },
                "messageType": "Outgoing",
                "protocol": "json",
            },
            "fields": {"a": {"simpleValue": "123"}},
        },
        "bodyBase64": "eyJhIjogIjEyMyJ9",
    },
    {
        "type": "message",
        "timestamp": {"nano": 307080000, "epochSecond": 1668603187},
        "messageType": "Incoming",
        "direction": "IN",
        "sessionId": "ds-lib-session1",
        "attachedEventIds": [],
        "messageId": "ds-lib-session1:first:1668603186732416805",
        "body": {
            "metadata": {
                "id": {"connectionId": {"sessionAlias": "ds-lib-session1"}, "sequence": "1668603186732416805"},
                "messageType": "Incoming",
                "protocol": "json",
            },
            "fields": {"msg_for_get_by_id_num": {"simpleValue": "1"}},
        },
        "bodyBase64": "eyJtc2dfZm9yX2dldF9ieV9pZF9udW0iOiAiMSJ9",
    },
    {
        "type": "message",
        "timestamp": {"nano": 307080000, "epochSecond": 1668603187},
        "messageType": "Incoming",
        "direction": "IN",
        "sessionId": "ds-lib-session1",
        "attachedEventIds": [],
        "messageId": "ds-lib-session1:first:1668603186732416806",
        "body": {
            "metadata": {
                "id": {"connectionId": {"sessionAlias": "ds-lib-session1"}, "sequence": "1668603186732416806"},
                "messageType": "Incoming",
                "protocol": "json",
            },
            "fields": {"msg_for_get_by_id_num": {"simpleValue": "2"}},
        },
        "bodyBase64": "eyJtc2dfZm9yX2dldF9ieV9pZF9udW0iOiAiMiJ9",
    },
]
