name: CI Dependencies Test

on:
  pull_request:
    branches:
      - master
      - release_*

jobs:
  test:
    strategy:
      matrix:
#        providers: [ rdp, rdp5, rdp6, lwdp, lwdp1 ]
        providers: [ lwdp, lwdp1 ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install th2-data-services[${{ matrix.providers }}]
      - name: Test dependencies
        run: |
          pip install pytest -q
          pytest tests/tests_unit/test_dependencies/ --provider=${{ matrix.providers }}
