name: CI Dependencies Test

on:
  pull_request:
    branches:
      - master
      - release_*

jobs:
  test:
    strategy:
      matrix:
#        providers: [ rdp, rdp5, rdp6, lwdp, lwdp1 ]
        providers: [ lwdp ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64
      - name: Install dependencies
        run: |
          pip install th2-data-services[${{ matrix.providers }}]
          pip install importlib-metadata
      - name: Test dependencies
        run: |
          pip install pytest -q
          pytest tests/tests_unit/test_dependencies/ --provider=${{ matrix.providers }}
