name: CI Dev Dependencies Test

on:
  pull_request:
    branches:
      - dev_*
      - TH2-*
      - th2-*
      - pypi_*

jobs:
  test:
    strategy:
      matrix:
#        providers: [ rdp, rdp5, rdp6, lwdp, lwdp1 ]
        providers: [ lwdp, lwdp1 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          # Install Package From Local Directory
          pip install --pre -e .[${{ matrix.providers }}]
      - name: Test dependencies
        run: |
          pip install pytest -q
          pytest tests/tests_unit/test_dependencies/ --provider=${{ matrix.providers }}
