name: CI tests Py 3.10 (for master only)

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        py_version: [ '3.10' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py_version }}
          architecture: x64

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-xdist

      - name: Test with pytest
        run: |
          export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
          bash run_unit_tests.sh
