name: 'Vulnerabilities scanning'

on:
  push:

env:
  DEP_PATH: requirements.txt

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master
#      - name: Security vulnerabilities scan
#        continue-on-error: false
#        uses: aufdenpunkt/python-safety-check@043b9bf55528dacdc4ee3956a162ee9a92f00188
#        with:
#          scan_requirements_file_only: 'true'
#          safety_args: '--policy-file .safety-policy.yaml'

      - name: pyupio/safety-action
        uses: pyupio/safety-action@v1.0.1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
